[package]
name = "wavsen"
version = "0.1.0"

[lib]
name = "wavsen"
module = "wavsen"
archive = "wavsen"
discovery = "module"

[usage]
public-definitions = ["WAVSEN_HAS_VAAPI=1"]

[dependencies.rstd-core]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-cppstd]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-log]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[dependencies.rstd-dlopn]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[dependencies.vvk]
git = "https://github.com/litocpp/vvk.git"
visibility = "public"

[external-dependencies.pkg-config.libavformat]
module = "libavformat"
version = ">= 58"
visibility = "public"

[external-dependencies.pkg-config.libavcodec]
module = "libavcodec"
version = ">= 58"
visibility = "public"

[external-dependencies.pkg-config.libavutil]
module = "libavutil"
version = ">= 56"
visibility = "public"

[external-dependencies.pkg-config.libswscale]
module = "libswscale"
version = ">= 5"
visibility = "public"

[external-dependencies.pkg-config.libswresample]
module = "libswresample"
version = ">= 3"
visibility = "public"

[external-dependencies.pkg-config.libva]
module = "libva"
visibility = "public"

[external-dependencies.pkg-config.libva-drm]
module = "libva-drm"
visibility = "public"

[external-dependencies.pkg-config.libpulse]
module = "libpulse"
version = ">= 14.0"
visibility = "private"

[external-dependencies.cmake.wavsen-shader]
find-package = "WavsenShader"
path = "shaders"
targets = [{ name = "WavsenShader::nv12_to_rgba", visibility = "private" }]
