[workspace]
name = "wavsen"
members = [
  "src/ffi/ffmpeg",
  "src/ffi/pulse",
  "src/decode",
  "src/video",
  "src/audio",
]
default-members = ["src/decode", "src/video", "src/audio"]

[workspace.package]
version = "0.1.0"
