[package]
name = "wavsen-ffi-pulse"
version.workspace = true
module = "pulse"

[library]
archive = "wavsen_ffi_pulse"
discovery = "explicit"
sources = ["pulse.cppm", "pulse.cpp"]

[usage]
private-options = [
  "-fPIC",
  "-fsized-deallocation",
  "-Wall",
  "-Wextra",
  "-Wpedantic",
  "-Wno-missing-field-initializers",
]

[dependencies.rstd-core]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[dependencies.rstd-dlopn]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[external-dependencies.pkg-config.libpulse]
module = "libpulse"
version = ">= 14.0"
visibility = "private"
