[package]
name = "wavsen-audio"
version.workspace = true
module = "wavsen.audio"

[library]
archive = "wavsen_audio"
discovery = "explicit"
sources = [
  "byte_stream.cppm",
  "audio_device.cppm",
  "sound_manager.cppm",
  "stream_decoder.cppm",
  "av_player.cppm",
  "audio_capture.cppm",
  "audio_gain.cppm",
  "audio_capture_window.cppm",
  "audio.cppm",
  "stream_decoder.cpp",
  "sound_manager.cpp",
  "av_player.cpp",
  "audio_device_pulse.cpp",
  "audio_capture_pulse.cpp",
]

[usage]
private-options = ["-fsized-deallocation"]

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-cppstd]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-log]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[dependencies.wavsen-ffi-ffmpeg]
path = "../ffi/ffmpeg"
visibility = "public"

[dependencies.wavsen-ffi-pulse]
path = "../ffi/pulse"
visibility = "private"
