[package]
name = "wavsen-video"
version.workspace = true
module = "wavsen.video"

[library]
archive = "wavsen_video"
discovery = "explicit"
sources = [
  "wavsen_video.cppm",
  "vk_device.cppm",
  "video_decoder.cppm",
  "yuv_to_rgba.cppm",
  "presenter.cppm",
  "vk_device.cpp",
  "video_decoder.cpp",
  "yuv_to_rgba.cpp",
]

[usage]
private-options = ["-fPIC", "-fsized-deallocation"]

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dependencies.rstd-cppstd]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[dependencies.rstd-log]
git = "https://github.com/litocpp/rstd.git"
visibility = "private"

[dependencies.wavsen-ffi-ffmpeg]
path = "../ffi/ffmpeg"
visibility = "public"

[dependencies.vvk]
git = "https://github.com/litocpp/vvk.git"
visibility = "public"

[dependencies.wavsen-shader]
cmake = "WavsenShader"
target = "WavsenShader::nv12_to_rgba"
path = "../../shaders"
visibility = "private"
